name: Caller Workflow  
  
on:  
  push:  
    branches:  
      - main  
    paths:  
      - '.github/workflows/caller-workflows.yml'  
  workflow_dispatch:  
  
jobs:  
  # Job to call the reusable workflow  
  call-reusable-workflow:  
    runs-on: ubuntu-latest  
  
    steps:  
      # Step to call the reusable workflow  
      - name: Call reusable workflow  
        uses: ./.github/workflows/reusable-print-message.yml  
        with:  
          message: ${{ github.event.inputs.message }}  
  
      # Step to print the message from the caller workflow  
      - name: Print caller message  
        run: |  
          echo "Message from caller workflow: ${{ github.event.inputs.message }}"  
