name: Caller Workflow  
  
on:  
  push:  
    branches:  
      - main  
    paths:  
      - '.github/workflows/caller-workflows.yml'  
  workflow_dispatch:  
  
jobs:  
  # Job to call the reusable workflow  
  call-reusable-workflow:  
    runs-on: ubuntu-latest  
  
    steps:  
      - name: Call Reusable Workflow  
        run: ./.github/workflows/reusable-print-message.yml "Hello from the caller workflow!"  
