#HI  
name: Caller Workflow  
  
on:  
  push:  
    branches:  
      - main  
    paths:  
      - '.github/workflows/caller-workflows.yml'  
  workflow_dispatch:  
  
jobs:  
  # Job to call the reusable workflow  
  call-reusable-workflow:  
    # Specifies the path to the reusable workflow  
    uses: ./.github/workflows/reusable-print-message.yml  
    with:  
      # Passes the message to the reusable workflow  
      message: "Hello from the caller workflow!"  
  
    steps:  
      # Step to print the message from the caller workflow  
      - name: Print caller message  
        run: echo "Message from caller workflow: Hello from the caller workflow!"  
