name: Debugging and Monitoring Workflow

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/deploy-to-azure.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run missing script
      run: bash ./missing-script.sh
